Check env variables before start

diff --git a/scripts/rabbitmq-server b/scripts/rabbitmq-server
--- a/scripts/rabbitmq-server
+++ b/scripts/rabbitmq-server
@@ -113,6 +113,7 @@ fi
 set -f
 
 start_rabbitmq_server() {
+    check_start_params &&
     RABBITMQ_CONFIG_FILE=$RABBITMQ_CONFIG_FILE \
     exec ${ERL_DIR}erl \
         -pa ${RABBITMQ_EBIN_ROOT} \
@@ -144,10 +145,30 @@ start_rabbitmq_server() {
 }
 
 stop_rabbitmq_server() {
+    check_start_params
+
     RABBITMQCTL="$(dirname "$0")/rabbitmqctl"
 
     if ${RABBITMQCTL} -n ${RABBITMQ_NODENAME} status >/dev/null 2>&1; then
         ${RABBITMQCTL} -n ${RABBITMQ_NODENAME} stop
+    fi
+}
+
+check_start_params() {
+    check_not_empty "RABBITMQ_BOOT_MODULE" $RABBITMQ_BOOT_MODULE
+    check_not_empty "RABBITMQ_NAME_TYPE" $RABBITMQ_NAME_TYPE
+    check_not_empty "RABBITMQ_NODENAME" $RABBITMQ_NODENAME
+    check_not_empty "SASL_BOOT_FILE" $SASL_BOOT_FILE
+    check_not_empty "RABBITMQ_IO_THREAD_POOL_SIZE" $RABBITMQ_IO_THREAD_POOL_SIZE
+}
+
+check_not_empty() {
+    if [ "x" = "x$2" ]; then
+        echo "Error: ENV variable should be defined: $1. 
+       Please check rabbitmq-env and rabbitmq-defaul script files"
+        exit 78
+    else
+        echo "x$2"
     fi
 }
 
