try the docker cask again for M1

diff --git a/.github/workflows/oci.yaml b/.github/workflows/oci.yaml
--- a/.github/workflows/oci.yaml
+++ b/.github/workflows/oci.yaml
@@ -131,13 +131,11 @@ jobs:
             exit 1
           fi
 
-          brew install docker docker-buildx colima
-
-          # Link the Docker Buildx plugin so it's understood by the docker CLI
-          mkdir -p ~/.docker/cli-plugins
-          ln -sfn /usr/local/opt/docker-buildx/bin/docker-buildx ~/.docker/cli-plugins/docker-buildx
-
-          colima start
+          HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
+          sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
+          open -a /Applications/Docker.app --args --unattended --accept-license
+          echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
+          while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done
       - name: Download context
         uses: actions/download-artifact@v4
         with:
