Revert "Try with emulation"
This reverts commit 5fc300cf53749abb7b0a3915b1396d2da89e712f.

diff --git a/.github/workflows/oci.yaml b/.github/workflows/oci.yaml
--- a/.github/workflows/oci.yaml
+++ b/.github/workflows/oci.yaml
@@ -14,7 +14,7 @@ concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
   cancel-in-progress: true
 jobs:
-  build-publish-dev-bazel:
+  generate-context:
     runs-on: ubuntu-latest
     env:
       CONTEXT_DIR: context
@@ -25,7 +25,6 @@ jobs:
         uses: actions/checkout@v4
         with:
           path: rabbitmq-server
-
       - name: Configure Bazel
         working-directory: rabbitmq-server
         run: |
@@ -77,43 +76,134 @@ jobs:
             echo "PUSH=false" >> $GITHUB_OUTPUT
           fi
 
+  build-amd64:
+    needs: generate-context
+    runs-on: ubuntu-latest
+    outputs:
+      full_tag: ${{ steps.tag.outputs.full_tag }}
+    steps:
+      - name: Download context
+        uses: actions/download-artifact@v4
+        with:
+          name: context
+      - name: Compute Tag
+        id: tag
+        run: |
+          echo "full_tag=${{ env.REGISTRY_IMAGE }}:${{ env.VERSION }}-amd64" | tee -a $GITHUB_OUTPUT
       - name: Expose GitHub Runtime
         uses: crazy-max/ghaction-github-runtime@v3
-
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
-
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
-
       - name: Login to DockerHub
-        if: steps.authorized.outputs.PUSH == 'true'
+        if: needs.generate-context.outputs.PUSH == 'true'
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_PASSWORD }}
-
       - name: Docker build
         run: |
-          if [ "${{ steps.authorized.outputs.PUSH }}" == "true" ]; then
+          if [ "${{ needs.generate-context.outputs.PUSH }}" == "true" ]; then
             PUSH_FLAG="--push"
           else
             PUSH_FLAG=""
           fi
 
+          docker buildx build \
+            --cache-from=type=gha \
+            --cache-to=type=gha \
+            --platform=linux/amd64 \
+            ${PUSH_FLAG} \
+            --tag ${{ steps.tag.outputs.full_tag }} \
+            .
+
+  build-arm64:
+    needs: generate-context
+    runs-on: macos-14
+    outputs:
+      full_tag: ${{ steps.tag.outputs.full_tag }}
+    steps:
+      - name: Install Docker
+        timeout-minutes: 10
+        run: |
+          HOST_ARCH="$(uname -m)"
+          echo "Host Arch: $HOST_ARCH"
+          if [[ "$HOST_ARCH" != "arm64" ]]; then
+            echo "ERROR: Runner arch is not arm64"
+            exit 1
+          fi
+
+          brew install docker docker-buildx
+
+          # Link the Docker Buildx plugin so it's understood by the docker CLI
+          mkdir -p ~/.docker/cli-plugins
+          ln -sfn /opt/homebrew/lib/docker/cli-plugins/docker-buildx ~/.docker/cli-plugins/docker-buildx
+
+          docker buildx install
+      - name: Download context
+        uses: actions/download-artifact@v4
+        with:
+          name: context
+      - name: Compute Tag
+        id: tag
+        run: |
+          echo "full_tag=${{ env.REGISTRY_IMAGE }}:${{ env.VERSION }}-arm64" | tee -a $GITHUB_OUTPUT
+      - name: Expose GitHub Runtime
+        uses: crazy-max/ghaction-github-runtime@v3
+      - name: Login to DockerHub
+        if: needs.generate-context.outputs.PUSH == 'true'
+        uses: docker/login-action@v3
+        with:
+          username: ${{ secrets.DOCKERHUB_USERNAME }}
+          password: ${{ secrets.DOCKERHUB_PASSWORD }}
+      - name: Docker build
+        run: |
+          if [ "${{ needs.generate-context.outputs.PUSH }}" == "true" ]; then
+            PUSH_FLAG="--push"
+          else
+            PUSH_FLAG=""
+          fi
+
+          docker buildx create \
+            --name container \
+            --driver=docker-container
+
+          docker buildx build \
+            --builder=container \
+            --cache-from=type=gha \
+            --cache-to=type=gha \
+            --platform=linux/arm64 \
+            ${PUSH_FLAG} \
+            --tag ${{ steps.tag.outputs.full_tag }} \
+            .
+
+  build-publish-dev-bazel:
+    runs-on: ubuntu-latest
+    needs:
+      - generate-context
+      - build-amd64
+      - build-arm64
+    steps:
+      - name: Create and Push Manifest
+        if: needs.generate-context.outputs.PUSH == 'true'
+        run: |
           TAG_1="${{ env.VERSION }}"
 
           REF_NAME="${{ github.ref_name }}"
           TAG_2="${REF_NAME//\//-}"
 
-          docker buildx build \
-            --cache-from=type=gha \
-            --cache-to=type=gha \
-            --platform=linux/amd64,linux/arm64 \
-            ${PUSH_FLAG} \
-            --tag ${{ env.REGISTRY_IMAGE }}:$TAG_1 \
-            --tag ${{ env.REGISTRY_IMAGE }}:$TAG_2 \
-            ${{ env.CONTEXT_DIR }}
+          docker manifest create \
+            ${{ env.REGISTRY_IMAGE }}:${TAG_1} \
+            --amend ${{ needs.build-amd64.outputs.full_tag }} \
+            --amend ${{ needs.build-arm64.outputs.full_tag }}
+
+          docker manifest push ${{ env.REGISTRY_IMAGE }}:${TAG_1}
+
+          docker manifest create \
+            ${{ env.REGISTRY_IMAGE }}:${TAG_2} \
+            --amend ${{ needs.build-amd64.outputs.full_tag }} \
+            --amend ${{ needs.build-arm64.outputs.full_tag }}
+
+          docker manifest push ${{ env.REGISTRY_IMAGE }}:${TAG_2}
 
   summary-oci:
     needs:
