Sync /workflows/update-otp-patches.yaml with main
(cherry picked from commit 18c9352ab81d539f62245978430e9e84d6b356f1)

# Conflicts:
#	.github/workflows/update-otp-for-oci.yaml

diff --git a/.github/workflows/update-otp-for-oci.yaml b/.github/workflows/update-otp-for-oci.yaml
--- a/.github/workflows/update-otp-for-oci.yaml
+++ b/.github/workflows/update-otp-for-oci.yaml
@@ -9,6 +9,7 @@ jobs:
     runs-on: ubuntu-20.04
     strategy:
       max-parallel: 1
+      fail-fast: false
       matrix:
 <<<<<<< HEAD:.github/workflows/update-otp-for-oci.yaml
 <<<<<<< HEAD:.github/workflows/update-otp-for-oci.yaml
@@ -28,8 +29,16 @@ jobs:
         - "25.1"
         - "25.2"
         include:
+        - erlang_version: "24.3"
+          name: '24'
+          branch: v3.10.x
+          labels: |
+            backport-v3.9.x
         - erlang_version: "25.0"
           name: '25_0'
+          branch: main
+          labels: |
+            backport-v3.11.x
         - erlang_version: "25.1"
           name: '25_1'
           branch: main
@@ -51,6 +60,8 @@ jobs:
     steps:
     - name: CHECKOUT REPOSITORY
       uses: actions/checkout@v3
+      with:
+        ref: ${{ matrix.branch }}
     - name: SKIP IF THE PR ALREADY EXISTS
       id: check-for-branch
       run: |
@@ -64,11 +75,39 @@ jobs:
         TAG_NAME=$(curl -s GET https://api.github.com/repos/erlang/otp/tags \
           | jq -r 'map(select(.name | contains("OTP-${{ matrix.erlang_version }}"))) | first | .name')
 
+<<<<<<< HEAD:.github/workflows/update-otp-for-oci.yaml
         wget --continue --quiet --output-document="/tmp/OTP.tar.gz" "https://github.com/erlang/otp/archive/${TAG_NAME}.tar.gz" && \
         SHA=$(shasum -a 256 "/tmp/OTP.tar.gz" | awk '{print $1}')
 
         echo "::set-output name=VERSION::${TAG_NAME#OTP-}"
+=======
+        if [[ -z "${VERSION}" ]]; then
+          echo "Failed to determine latest VERSION for OTP-${{ matrix.erlang_version }}"
+          exit 1
+        fi
+
+        ARCHIVE_RBE_URL="https://github.com/erlang/otp/releases/download/${TAG_NAME}/otp_src_${VERSION}.tar.gz"
+        wget --continue --quiet --output-document="/tmp/otp_src_${VERSION}.tar.gz" "${ARCHIVE_RBE_URL}"
+        SHA="$(shasum -a 256 "/tmp/otp_src_${VERSION}.tar.gz" | awk '{print $1}')"
+
+        if [[ -z "${SHA}" ]]; then
+          echo "Failed to determine SHA for ${TAG_NAME}"
+          exit 1
+        fi
+
+        ARCHIVE_OCI_URL="https://github.com/erlang/otp/archive/OTP-${VERSION}.tar.gz"
+        wget --continue --quiet --output-document="/tmp/OTP-${VERSION}.tar.gz" "${ARCHIVE_OCI_URL}"
+        SHA2="$(shasum -a 256 "/tmp/OTP-${VERSION}.tar.gz" | awk '{print $1}')"
+
+        if [[ -z "${SHA2}" ]]; then
+          echo "Failed to determine SHA2 for ${TAG_NAME}"
+          exit 1
+        fi
+
+        echo "::set-output name=VERSION::${VERSION}"
+>>>>>>> 18c9352ab8 (Sync /workflows/update-otp-patches.yaml with main):.github/workflows/update-otp-patches.yaml
         echo "::set-output name=SHA::${SHA}"
+        echo "::set-output name=SHA2::${SHA2}"
     - name: MODIFY VERSION FILE
       if: steps.check-for-branch.outputs.c != 0
       run: |
@@ -84,9 +123,35 @@ jobs:
         echo "$(cat WORKSPACE | buildozer 'set urls ["https://github.com/erlang/otp/archive/OTP-${{ steps.fetch-version.outputs.VERSION }}.tar.gz"]' -:otp_src_${{ matrix.name }})" > WORKSPACE
         echo "$(cat WORKSPACE | buildozer 'set sha256 "${{ steps.fetch-version.outputs.SHA2 }}"' -:otp_src_${{ matrix.name }})" > WORKSPACE
 
-        sed -i"_orig" "s/${OLD_SHA}/${{ steps.fetch-version.outputs.SHA }}" WORKSPACE
-        sed -i"_orig" "s/${OLD_VERSION}/${{ steps.fetch-version.outputs.VERSION }}" WORKSPACE
-        rm *_orig
+        cat << EOF > replacer.mjs
+        import { readFile, writeFile } from 'node:fs/promises';
+        let [_node, _script, s, p, r] = process.argv;
+        let source = await readFile(s, 'utf-8');
+        let pattern = await readFile(p, 'utf-8');
+        let replacement = await readFile(r, 'utf-8');
+        if (!source.includes(pattern)) process.exit(1);
+        let updated = source.replace(pattern, replacement);
+        await writeFile(s, updated);
+        EOF
+
+        cat << EOF > old.txt
+                internal_erlang_from_github_release(
+                    name = "${{ matrix.name }}",
+                    sha256 = "${OLD_SHA}",
+                    version = "${OLD_VERSION}",
+                ),
+        EOF
+
+        cat << EOF > new.txt
+                internal_erlang_from_github_release(
+                    name = "${{ matrix.name }}",
+                    sha256 = "${{ steps.fetch-version.outputs.SHA }}",
+                    version = "${{ steps.fetch-version.outputs.VERSION }}",
+                ),
+        EOF
+
+        node replacer.mjs WORKSPACE old.txt new.txt
+        rm replacer.mjs old.txt new.txt
 
         set -x
         git diff
@@ -97,6 +162,7 @@ jobs:
         token: ${{ secrets.REPO_SCOPED_TOKEN }}
         committer: GitHub <noreply@github.com>
         author: GitHub <noreply@github.com>
+<<<<<<< HEAD:.github/workflows/update-otp-for-oci.yaml
         title: Adopt otp ${{ steps.fetch-version.outputs.VERSION }} for OCI workflow
         commit-message: |
           Adopt otp ${{ steps.fetch-version.outputs.VERSION }} for OCI workflow
@@ -105,4 +171,16 @@ jobs:
           backport-v3.9.x
           backport-v3.8.x
         branch: bump-otp-for-oci
+=======
+        title: Adopt otp ${{ steps.fetch-version.outputs.VERSION }}
+        body: >
+           Automated changes created by
+           ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+           using the [create-pull-request](https://github.com/peter-evans/create-pull-request)
+           GitHub action in the ${{ github.workflow }} workflow.
+        commit-message: |
+          Adopt otp ${{ steps.fetch-version.outputs.VERSION }}
+        labels: ${{ matrix.labels }}
+        branch: bump-otp-${{ matrix.erlang_version }}
+>>>>>>> 18c9352ab8 (Sync /workflows/update-otp-patches.yaml with main):.github/workflows/update-otp-patches.yaml
         delete-branch: true
