Further adjustments to otp/elixir auto-bump workflows

diff --git a/.github/workflows/update-elixir-patches.yaml b/.github/workflows/update-elixir-patches.yaml
--- a/.github/workflows/update-elixir-patches.yaml
+++ b/.github/workflows/update-elixir-patches.yaml
@@ -37,7 +37,12 @@ jobs:
         wget --continue --quiet --output-document="/tmp/elixir.tar.gz" "https://github.com/elixir-lang/elixir/archive/${TAG_NAME}.tar.gz" && \
         SHA=$(shasum -a 256 "/tmp/elixir.tar.gz" | awk '{print $1}')
 
-        echo "::set-output name=VERSION::${TAG_NAME#OTP-}"
+        if [ -n "${SHA}" ]; then
+          echo "Failed to determine SHA for ${TAG_NAME}"
+          exit 1
+        fi
+
+        echo "::set-output name=VERSION::${TAG_NAME}"
         echo "::set-output name=SHA::${SHA}"
     - name: MODIFY VERSION FILE
       if: steps.check-for-branch.outputs.c != 0
@@ -45,6 +50,7 @@ jobs:
         sudo npm install --global --silent @bazel/buildozer
 
         LINE=$(grep -n 'name_suffix = "${{ matrix.name_suffix }}",' bazel/toolchains/BUILD.bazel | awk -F  ":" '{print $1}')
+        LINE=$(($LINE-1))
 
         buildozer 'set sha256 "${{ steps.fetch-version.outputs.SHA }}"' \
           //bazel/toolchains:%${LINE}
