Use ubuntu-20.04 in actions as the base OS
The ubuntu-latest tag is being switched to 22.04, and seems to be
causing some issues

(cherry picked from commit d7200647ca244169ab80c11ef8d3f7329d16da21)
(cherry picked from commit 145e1570c32e137b43ae4b293332ac2f5a394f64)

# Conflicts:
#	.github/workflows/test-selenium.yaml
#	.github/workflows/update-elixir-patches.yaml
(cherry picked from commit 1b6582e91b7022d3fa5eaf26d69f8ba6b16147aa)

# Conflicts:
#	.github/workflows/test-mixed-versions.yaml

diff --git a/.github/workflows/update-elixir-patches.yaml b/.github/workflows/update-elixir-patches.yaml
--- a/.github/workflows/update-elixir-patches.yaml
+++ b/.github/workflows/update-elixir-patches.yaml
@@ -1,20 +1,20 @@
-name: Update OTP Versions for OCI Workflow
+name: Update Elixir Patch Versions for Bazel Based Workflows
 on:
   schedule:
   - cron: '0 3 * * *'
   workflow_dispatch:
 jobs:
-  update-rbe-images:
-    name: Update OTP Versions
+  update-toolchains:
+    name: Update Elixir Versions
     runs-on: ubuntu-20.04
     strategy:
       max-parallel: 1
       matrix:
-        erlang_version:
-        - "25.0"
         include:
-        - erlang_version: "25.0"
-          name: '25'
+        - elixir_version: "1.13"
+          name: '1_13'
+        - elixir_version: "1.14"
+          name: '1_14'
     timeout-minutes: 10
     steps:
     - name: CHECKOUT REPOSITORY
@@ -23,19 +23,30 @@ jobs:
       id: check-for-branch
       run: |
         set +e
-        git ls-remote --exit-code --heads origin bump-otp-for-oci
+        git ls-remote --exit-code --heads origin bump-elixir-${{ matrix.elixir_version }}
         echo "::set-output name=c::$?"
     - name: DETERMINE LATEST PATCH & SHA
       if: steps.check-for-branch.outputs.c != 0
       id: fetch-version
       run: |
-        TAG_NAME=$(curl -s GET https://api.github.com/repos/erlang/otp/tags \
-          | jq -r 'map(select(.name | contains("OTP-${{ matrix.erlang_version }}"))) | first | .name')
+        TAG_NAME=$(curl -s GET https://api.github.com/repos/elixir-lang/elixir/tags?per_page=100 \
+          | jq -r 'map(select(.name | contains("v${{ matrix.elixir_version }}"))) | first | .name')
 
-        wget --continue --quiet --output-document="/tmp/OTP.tar.gz" "https://github.com/erlang/otp/archive/${TAG_NAME}.tar.gz" && \
-        SHA=$(shasum -a 256 "/tmp/OTP.tar.gz" | awk '{print $1}')
+        if [[ -z "${TAG_NAME}" ]]; then
+          echo "Failed to determine latest TAG_NAME for v${{ matrix.elixir_version }}"
+          exit 1
+        fi
 
-        echo "::set-output name=VERSION::${TAG_NAME#OTP-}"
+        ARCHIVE_URL="https://github.com/elixir-lang/elixir/archive/${TAG_NAME}.tar.gz"
+        wget --continue --quiet --output-document="/tmp/elixir.tar.gz" "${ARCHIVE_URL}" && \
+        SHA="$(shasum -a 256 "/tmp/elixir.tar.gz" | awk '{print $1}')"
+
+        if [ -z "${SHA}" ]; then
+          echo "Failed to determine SHA for ${TAG_NAME}"
+          exit 1
+        fi
+
+        echo "::set-output name=VERSION::${TAG_NAME#v}"
         echo "::set-output name=SHA::${SHA}"
     - name: MODIFY VERSION FILE
       if: steps.check-for-branch.outputs.c != 0
@@ -48,12 +59,8 @@ jobs:
         echo "$(cat MODULE.bazel | buildozer 'set sha256 "${{ steps.fetch-version.outputs.SHA }}"' -:${{ matrix.name }})" > MODULE.bazel
         echo "$(cat MODULE.bazel | buildozer 'set version "${{ steps.fetch-version.outputs.VERSION }}"' -:${{ matrix.name }})" > MODULE.bazel
 
-        echo "$(cat WORKSPACE | buildozer 'set downloaded_file_path "OTP-${{ steps.fetch-version.outputs.VERSION }}.tar.gz"' -:otp_src_${{ matrix.name }})" > WORKSPACE
-        echo "$(cat WORKSPACE | buildozer 'set urls ["https://github.com/erlang/otp/archive/OTP-${{ steps.fetch-version.outputs.VERSION }}.tar.gz"]' -:otp_src_${{ matrix.name }})" > WORKSPACE
-        echo "$(cat WORKSPACE | buildozer 'set sha256 "${{ steps.fetch-version.outputs.SHA2 }}"' -:otp_src_${{ matrix.name }})" > WORKSPACE
-
-        sed -i"_orig" "s/${OLD_SHA}/${{ steps.fetch-version.outputs.SHA }}" WORKSPACE
-        sed -i"_orig" "s/${OLD_VERSION}/${{ steps.fetch-version.outputs.VERSION }}" WORKSPACE
+        sed -i"_orig" "s/${OLD_SHA}/${{ steps.fetch-version.outputs.SHA }}/" WORKSPACE
+        sed -i"_orig" "s/${OLD_VERSION}/${{ steps.fetch-version.outputs.VERSION }}/" WORKSPACE
         rm *_orig
 
         set -x
@@ -65,12 +72,13 @@ jobs:
         token: ${{ secrets.REPO_SCOPED_TOKEN }}
         committer: GitHub <noreply@github.com>
         author: GitHub <noreply@github.com>
-        title: Adopt otp ${{ steps.fetch-version.outputs.VERSION }} for OCI workflow
+        title: Adopt elixir ${{ steps.fetch-version.outputs.VERSION }}
         commit-message: |
-          Adopt otp ${{ steps.fetch-version.outputs.VERSION }} for OCI workflow
+          Adopt elixir ${{ steps.fetch-version.outputs.VERSION }}
         labels: |
+          backport-v3.11.x
           backport-v3.10.x
           backport-v3.9.x
           backport-v3.8.x
-        branch: bump-otp-for-oci
+        branch: bump-elixir-${{ matrix.elixir_version }}
         delete-branch: true
