Try to make two actions workflows more robust
Sometimes the update-[otp|elixir]-patches.yaml workflows fail to
determine a version. They should error in this case. There was a check
in place for this, but it does not seem to be working, so this updates
it.

diff --git a/.github/workflows/update-elixir-patches.yaml b/.github/workflows/update-elixir-patches.yaml
--- a/.github/workflows/update-elixir-patches.yaml
+++ b/.github/workflows/update-elixir-patches.yaml
@@ -34,10 +34,15 @@ jobs:
         TAG_NAME=$(curl -s GET https://api.github.com/repos/elixir-lang/elixir/tags?per_page=100 \
           | jq -r 'map(select(.name | contains("v${{ matrix.elixir_version }}"))) | first | .name')
 
-        wget --continue --quiet --output-document="/tmp/elixir.tar.gz" "https://github.com/elixir-lang/elixir/archive/${TAG_NAME}.tar.gz" && \
-        SHA=$(shasum -a 256 "/tmp/elixir.tar.gz" | awk '{print $1}')
+        if [ x"${TAG_NAME}" = x ]; then
+          echo "Failed to determine latest TAG_NAME for v${{ matrix.elixir_version }}"
+          exit 1
+        fi
 
-        if [ -z "${SHA}" ]; then
+        wget --continue --quiet --output-document="/tmp/elixir.tar.gz" "https://github.com/elixir-lang/elixir/archive/${TAG_NAME}.tar.gz" && \
+        SHA="$(shasum -a 256 "/tmp/elixir.tar.gz" | awk '{print $1}')"
+
+        if [ x"${SHA}" = x ]; then
           echo "Failed to determine SHA for ${TAG_NAME}"
           exit 1
         fi
@@ -67,6 +72,13 @@ jobs:
         committer: GitHub <noreply@github.com>
         author: GitHub <noreply@github.com>
         title: Adopt elixir ${{ steps.fetch-version.outputs.VERSION }}
+        body: >
+           Automated changes created by
+           ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+           using the [create-pull-request](https://github.com/peter-evans/create-pull-request)
+           GitHub action
+
+           Source workflow: `${{ github.action_path }}`
         commit-message: |
           Adopt elixir ${{ steps.fetch-version.outputs.VERSION }}
         labels: |
diff --git a/.github/workflows/update-otp-patches.yaml b/.github/workflows/update-otp-patches.yaml
--- a/.github/workflows/update-otp-patches.yaml
+++ b/.github/workflows/update-otp-patches.yaml
@@ -33,11 +33,16 @@ jobs:
           | jq -r 'map(select(.name | contains("OTP-${{ matrix.erlang_version }}"))) | first | .name')
         VERSION=${TAG_NAME#OTP-}
 
+        if [ x"${VERSION}" = x ]; then
+          echo "Failed to determine latest VERSION for OTP-${{ matrix.erlang_version }}"
+          exit 1
+        fi
+
         ARCHIVE_URL="https://github.com/erlang/otp/releases/download/${TAG_NAME}/otp_src_${VERSION}.tar.gz"
         wget --continue --quiet --output-document="/tmp/OTP.tar.gz" "${ARCHIVE_URL}"
-        SHA=$(shasum -a 256 "/tmp/OTP.tar.gz" | awk '{print $1}')
+        SHA="$(shasum -a 256 "/tmp/OTP.tar.gz" | awk '{print $1}')"
 
-        if [ -z "${SHA}" ]; then
+        if [ x"${SHA}" = x ]; then
           echo "Failed to determine SHA for ${TAG_NAME}"
           exit 1
         fi
@@ -71,6 +76,13 @@ jobs:
         committer: GitHub <noreply@github.com>
         author: GitHub <noreply@github.com>
         title: Adopt otp ${{ steps.fetch-version.outputs.VERSION }}
+        body: >
+           Automated changes created by
+           ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
+           using the [create-pull-request](https://github.com/peter-evans/create-pull-request)
+           GitHub action
+
+           Source workflow: `${{ github.action_path }}`
         commit-message: |
           Adopt otp ${{ steps.fetch-version.outputs.VERSION }}
         labels: |
